### ISSUE TITLE
Add Pacstall in a GUI software center 

### ISSUE THREAD

**Issue by soumyaDghosh** [pacstall/chaotic-PPR#5]
This is a feature suggestion about adding a support for GUI software centers.

Recently a new and unique GUI software center came up for Ubuntu/Debian called [**software**](https://github.com/ubuntu-flutter-community/software/) which is written in flutter. This app until now have only snaps and debs/rpms, but it'll be awesome to have packages from pacstall here. According to one of the devs, this app uses, snapd.dart and packagekit.dart for calling and searching packages, can something similar API be made for Pacstall so that it can also be used here. Please think about this devs.

**Comment by Zahrun** [comment]
What is the status of this ? Depends on other tasks to be done before ? Needs development ? Needs infrastructure ? Needs funding ?

**Comment by Elsie19** [comment]
> What is the status of this ? Depends on other tasks to be done before ? Needs development ? Needs infrastructure ? Needs funding ?

We need infrastructure and funding yes.

**Comment by Zahrun** [comment]
> The primary building cluster is a node in [UFSCar](https://www2.ufscar.br/)s datacenter which is hosted in São Carlos, São Paulo, Brazil.

https://aur.chaotic.cx/ is hosted by a university

**Comment by Elsie19** [comment]
We are fairly confident we have the funding now!

**Comment by soumyaDghosh** [comment]
So, add a ppa, and pacstall packages showing up in the shiny new Ubuntu App Center?

**Comment by Elsie19** [comment]
If the Ubuntu app center can support normal apt repos, yes. It is not a PPA however.

**Comment by Zahrun** [comment]
Congratulations 🥳

**Comment by soumyaDghosh** [comment]
> If the Ubuntu app center can support normal apt repos, yes. It is not a PPA however.

Yes it does. It fetches all the debs

**Comment by Elsie19** [comment]
How does it display images and such?

**Comment by soumyaDghosh** [comment]
Not sure about that, will need to check the packagekit code

**Comment by Elsie19** [comment]
The PPR is functional at https://ppr.pacstall.dev.
